### ISSUE TITLE
Supports lists jobs for a workflow run in the case of more than 30

### ISSUE THREAD

**Issue by ishii1648** [Kesin11/CIAnalyzer#1309]
Hi, @Kesin11. I suggest to set `per_page` parameter in fetchJobs.

## Background

- We use CIAnalyzer in workflows where more than 30 jobs are executed.
- The fetchJobs function doesn't have the per_page parameter set, so it only retrieves up to the default 30 jobs.
  - https://github.com/Kesin11/CIAnalyzer/blob/v6.1.0/src/client/github_client.ts#L110-L118

## Considertation

- We may need to implement pagination, because the per_page parameter can only be set to a maximum of 100.
  - https://developer.github.com/v3/actions/workflow-jobs/#list-jobs-for-a-workflow-run
- However, workflows with more than 100 jobs are edge cases, so I think simply setting the per_page parameter to 100 should be sufficient.

Thanks.

**Comment by Kesin11** [comment]
@ishii1648 
Thanks to suggest improvement. I will see this issue at weekend.

**Comment by Kesin11** [comment]
@ishii1648 
I just released [v6.1.1](https://github.com/Kesin11/CIAnalyzer/releases/tag/v6.1.1) that add `per_page: 100` to `fetchJobs()`. Please try it.

> However, workflows with more than 100 jobs are edge cases, so I think simply setting the per_page parameter to 100 should be sufficient.

I agree. I would be happy if someone who needs this feature could create a pull request.

**Comment by ishii1648** [comment]
@Kesin11 
Thank you for your quick support.  I'll try it.
