### ISSUE TITLE
Request quota exhausted

### ISSUE THREAD

**Issue by christianherweg0807** [Kesin11/CIAnalyzer#267]
Hi Everyone,
thank you for this greate CI Swiss Knife!
For testing I tried to run this on my machine for about 100 Repositorys with Github Actions.
Collection worked great for about 15 repositorys, after that I crossed the x-ratelimit-limit (5000).

Is there a way around this quota?

P.s.: Great dashboard in you README. Would you share a template/howto build this?

**Comment by Kesin11** [comment]
@christianherweg0807  I'm sorry for late reply.

CIAnalyzer does not handle API rate limits. The first time CIAnalyzer try to collect some old build data and It may reach the rate limit, but next time it will continue from the last collected build number from LastRunStore file that created by the first time in `lastRunStore.path` (see [sample config](https://github.com/Kesin11/CIAnalyzer/blob/master/ci_analyzer.yaml#L54-L56))
As a result, normally it requires only a few API requests for repositories that have already collected ever once. If you repeat it several times, you should not reach the limit.

I published my dashboard. You can copy it to your DataStudio.
https://datastudio.google.com/reporting/71454c60-96f9-47e0-8dc6-2d5f98b60609/page/QFzEB

**Comment by Kesin11** [comment]
@christianherweg0807 Did you read it?
If you have any questions, please reply and reopen.
