### ISSUE TITLE
Insufficient error handling

### ISSUE THREAD

**Issue by yamatoya** [Kesin11/CIAnalyzer#353]
The problem occurs when you don't have enough GCP privileges.
Even when GCP is returning Access Denied, standard run will display another error on the console.
I think it's more friendly to see GCP's Access Denied.
Also, the error that appears when the lastRunStore bucket is null in config is hard to pinpoint with name.replace isn't function.

**Comment by Kesin11** [comment]
I guessed the following two issues from your comments. Are they correct?

1. Display unrelated errors when don't have enough GCP privileges.
2. Display unrelated errors when some configs are invalid.

And what do you want them to do?

**Comment by yamatoya** [comment]
It's correct.
I hope that when don't have enough GCP privileges, display that "GCP Access denied".
If an error message is displayed that clears the cause of the error, the error can be resolved quickly.
That's good for me.
Thanks

**Comment by Kesin11** [comment]
OK. I will try to make better error messages.

**Comment by Kesin11** [comment]
@yamatoya 
I just released [v4.3.1](https://github.com/Kesin11/CIAnalyzer/releases/tag/v4.3.1) that contains #389. Please try it!
