### ISSUE TITLE
An aborted Bitrise build sometimes had no logs.

### ISSUE THREAD

**Issue by takeya0x86** [Kesin11/CIAnalyzer#518]
Hi. I'm trying to analyze my projects using this app.
And I met error when aggregating Bitrise builds. An aborted Bitrise build sometimes had no logs. It seems to occur when a build was aborted very early time. In this case, the app couldn't save output files. It printed below message.

```
ERROR [BitriseClient@bitrise] 
{
  message: 'Request failed with status code 404',
  status: 404,
  statusText: 'Not Found',
  method: 'GET',
  baseUrl: 'https://api.bitrise.io/v0.1',
  url: 'apps/<slug>/builds/<slug>/log',
  params: undefined
}
ERROR [BitriseRunner@bitrise] Some error raised in 'myorg/myproject', so it skipped. 
```

Is there any workaround?

**Comment by Kesin11** [comment]
@takeya0x86  Hmmm, I have never met that situation. Can I reproduce it by aborting the build as soon as it starts?

If the builds with no logs are old and the more recent builds seem fine, you can modify the LastRunStore JSON yourself to make CIAnalyzer skip fetching the problem builds.

If your Bitrise config is using [the default](https://github.com/Kesin11/CIAnalyzer/blob/ca2c943040176465e7b5a5f2f03f5f9911600e3a/ci_analyzer.yaml#L55), CIAnalyzer creates JSON to `.ci_analyzer/last_run/bitrise.json`. It stored the last succeeded build number like this.

```bash
$ cat .ci_analyzer/last_run/bitrise.json
{
  "xxxxxxxxxxxxxx": { // Your app slug
    "lastRun": 8, // Last succeeded max build number
    "updatedAt": "2021-12-05T06:55:56.047Z"
  }
}
```

The next time CIAnalyzer is run, it will only fetch builds that newer than build number "8". Therefore, you can skip fetching the problem builds by modifying this JSON yourself. It may help your problem.

**Comment by takeya0x86** [comment]
Thanks to reply. I checked this situation again. It occurs when the build is *queued but aborted before running*. Typically the Rolling Builds feature triggered this situation when build queue is fulled. And this occurs many times (also future), so it is difficult to modify the last run file.

**Comment by Kesin11** [comment]
Thanks for reporting the detail. I'll try to reproduce it on my Bitrise app.

**Comment by takeya0x86** [comment]
@Kesin11 Thank you for fix it! I tried and it works fine!
