### ISSUE TITLE
How can I collect Jenkins Jobs recursively?

### ISSUE THREAD

**Issue by TakiTake** [Kesin11/CIAnalyzer#617]
Hi, I'd like to collect build info from Jenkins.
I manage several jobs in separate folders.

like
http://localhost:8080/job/Group1/job/job-abc/
http://localhost:8080/job/Group1/job/job-def/
http://localhost:8080/job/Group2/job/job-xyz/

In this case, I can't get jobs with following configuration
```
jenkins:
  baseUrl: http://localhost:8080
```

As a workaround solution, I use different baseUrl per Jenkins Folder http://localhost:8080job/Group1/, http://localhost:8080job/Group2/
Is there any good solution?

**Comment by Kesin11** [comment]
@TakiTake 
I was not familiar to folders, I have no idea better than your workaround unfortunately.

CIAnalyzer find a job by job name from "$JENKINS_BASE_URL/api/json"  https://github.com/Kesin11/CIAnalyzer/blob/9c87e25cdc16872289599abd5bd5ac761166af8b/src/client/jenkins_client.ts#L198
If you can't find your jobs that nested in folder from above API, also CIAnalyzer can't find jobs currently.

pull-requests are always welcome. If you make more better solution, I'm happy to review it.

**Comment by TakiTake** [comment]
Hi @Kesin11 ,
I created PR.
Please review it when you have time.

**Comment by Kesin11** [comment]
@TakiTake I released [v5.1.0](https://github.com/Kesin11/CIAnalyzer/releases/tag/v5.1.0)
Thank you for adding new feature!
